repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: cargo-fmt
        name: Rust format
        description: Run cargo fmt on files included in the commit.
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: true

    -   id: cargo-clippy
        name: Rust clippy
        description: Run cargo clippy on files included in the commit.
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
